server:
  port: 8080
  switch: 1
logging:
   config:
      classpath: logback-spring.xml

spring:
  datasource:
    url: jdbc:mysql://39.108.50.231:3306/maoyi?useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    max-idle: 10
    max-wait: 10000
    min-idle: 5
    initial-size: 5
    source1:
      name: orcl221
        # 使用druid数据源
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: oracle.jdbc.driver.OracleDriver
      filters: stat
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select * from dual
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      maxOpenPreparedStatements: 20
      useGlobalDataSourceStat: true


# mybatis.config= classpath:mybatis-config.xml
mybatis:
  typeAliasesPackage: org.spring.springboot.domain
  mapperLocations: mappers/*.xml

